Let services return null instead of throwing a NotFoundException
The exception should only be thrown by the controllers, with one
exception: The submitData method.